import {
  type FilterId,
  type FilterOption,
  type InstallTab,
} from "./types"

export const filters: FilterOption[] = [
  { id: "all", label: "All" },
  { id: "files", label: "Files" },
  { id: "buttons", label: "Buttons" },
  { id: "widgets", label: "Widgets" },
  { id: "forms", label: "Forms" },
  { id: "pricing-plans", label: "Pricing Plans" },
  { id: "hero-sections", label: "Hero Sections" },
  { id: "sliders", label: "Sliders" },
  { id: "contact-sections", label: "Contact Sections" },
  { id: "cards", label: "Cards" },
  { id: "keyboards", label: "Keyboards" },
  { id: "ai-tools", label: "AI Tools" },
]

export const hashToFilter: Record<string, FilterId> = {
  "#all": "all",
  "#home": "all",
  "#featured": "all",
  "#files": "files",
  "#glass-folder": "files",
  "#buttons": "buttons",
  "#magnetic-button": "buttons",
  "#book-call-button": "buttons",
  "#three-d-button": "buttons",
  "#widgets": "widgets",
  "#gradient-call-scheduler": "widgets",
  "#pixel-status-stack": "widgets",
  "#animated-dock": "widgets",
  "#forms": "forms",
  "#payment-method-card": "forms",
  "#pricing-plans": "pricing-plans",
  "#hero-sections": "hero-sections",
  "#aura-events-hero": "hero-sections",
  "#sliders": "sliders",
  "#project-spotlight-slider": "sliders",
  "#contact-sections": "contact-sections",
  "#kinetic-contact-section": "contact-sections",
  "#cards": "cards",
  "#morning-note-card": "cards",
  "#happy-files-card": "cards",
  "#keyboards": "keyboards",
  "#loop-pad-keyboard": "keyboards",
  "#ai-tools": "ai-tools",
  "#prompt-pad": "ai-tools",
  "#registry": "all",
  "#registry-output": "all",
}

export const filterToHash: Record<FilterId, string> = {
  all: "#all",
  files: "#files",
  buttons: "#buttons",
  widgets: "#widgets",
  forms: "#forms",
  "pricing-plans": "#pricing-plans",
  "hero-sections": "#hero-sections",
  sliders: "#sliders",
  "contact-sections": "#contact-sections",
  cards: "#cards",
  keyboards: "#keyboards",
  "ai-tools": "#ai-tools",
}

export const installTabs: InstallTab[] = ["npm", "pnpm", "yarn", "bun", "manual"]
